[package]
name = "master"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path= "../common" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"
