[package]
name = "chunkserver"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
master = { path = "../master" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
prost = "0.13"